fileRIndexing:
  class: File
  path: cellrangerIndexing/example_Indexing.R
gtfUrl: http://ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.gtf.gz
fastaUrl: http://ftp.ensembl.org/pub/release-104/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
fileRCount:
  class: File
  path: cellrangerCount/example_Count.R
directory-transcriptome:
  class: Directory
  path: cellrangerCount/10XGenome
fastqFolder:
  class: Directory
  path: cellrangerCount/fastqs
fileRH5:
  class: File
  path: cellrangerCount/example_H5.R
fileRScanno:
  class: File
  path: ScannoByGTF/example_Scanno.R
gtf:
  class: File
  path: ScannoByGTF/Homo_sapiens.GRCh38.104.gtf
fileRConvertMtxScannoBy:
  class: File
  path: convertMtxScannoBy/script_convertMtxScannoBy.R
skeletonConvertMtxScannoBy:
  class: File
  path: convertMtxScannoBy/skeleton_convertMtxScannoBy.R
fileRTopX:
  class: File
  path: TopX/example_TopX.R
fileRPermutationZero:
  class: File
  path: permutationClustering/Zero/script_PermutationZero.R
skeletonPermutationZero:
  class: File
  path: permutationClustering/Zero/permutationClusteringSW.R
fileRPermutationP:
  class: File
  path: permutationClustering/Permutation/script_PermutationClusteringP.R
skeletonPermutationP:
  class: File
  path: permutationClustering/Permutation/permutationClusteringSWP.R
index_array: 
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 105
  - 106
  - 107
  - 108
  - 109
  - 110
  - 111
  - 112
  - 113
  - 114
  - 115
  - 116
  - 117
  - 118
  - 119
  - 120
  - 121
  - 122
  - 123
  - 124
  - 125
  - 126
  - 127
  - 128
  - 129
  - 130
  - 131
  - 132
  - 133
  - 134
  - 135
  - 136
  - 137
  - 138
  - 139
  - 140
  - 141
  - 142
  - 143
  - 144
  - 145
  - 146
  - 147
  - 148
  - 149
  - 150
  - 151
  - 152
  - 153
  - 154
  - 155
  - 156
  - 157
  - 158
  - 159
  - 160
fileRPermutationFinal:
  class: File
  path: permutationClustering/Final/script_final.R
skeletonPermutationFinal:
  class: File
  path: permutationClustering/Final/skeleton_finalClustering.R
permutationFolder:
  class: Directory
  path: ResultsWorkflow
fileRPermAnalysis:
  class: File
  path: permAnalysis/script_Analysis.R 
skeletonPermAnalysis:
  class: File
  path: permAnalysis/skeleton_permAnalysis.R
fileRAutoencoder:
  class: File
  path: autoencoder/script_autoencoder.R
skeletonAutoencoder:
  class: File
  path: autoencoder/skeleton_autoencoder.R
index_array_autoencoder:
  - 1
projectName: projectName
fileRComet:
  class: File
  path: comet/script_Comet.R
skeletonComet:
  class: File
  path: comet/skeleton_Comet.R
prova:
  class: File
  path: output.csv
nCluster:
  class: File
  path: nCluster.txt
nCluster1:
  class: File
  path: nCluster1.txt
nCluster2:
  class: File
  path: nCluster2.txt
nCluster3:
  class: File
  path: nCluster3.txt
mtxProva:
  class: File
  path: matrice.csv
gtfProva:
  class: File
  path: genome.gtf
fileRPermutationPtsne:
  class: File
  path: permutationClustering/Permutation/script_PermutationClusteringP_tsne.R
fileRPermutationPgriph:
  class: File
  path: permutationClustering/Permutation/script_PermutationClusteringP_griph.R
index_prova:
  - 1
  - 2
fileRClusteringSeurat:
  class: File
  path: permutationClusteringSeurat/script_seurat.R
skeletonClusteringSeurat:
  class: File
  path: permutationClusteringSeurat/skeleton_seuratPermutation.R
fileRClusteringSharp:
  class: File
  path: permutationClusteringSharp/script_permutationClusteringSharp.R
skeletonClusteringSharp:
  class: File
  path: permutationClusteringSharp/skeleton_permutationClusteringSharp.R
